name: RAMS
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - absl-py=2.1.0
  - annotated-types=0.7.0
  - anyio=4.7.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - blinker=1.9.0
  - blosc=1.21.3
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.17.1
  - ca-certificates=2025.7.9
  - certifi=2025.7.9
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - clarabel=0.11.1
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - cvxpy=1.6.6
  - cvxpy-base=1.6.6
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dash=3.1.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dnspython=2.7.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - et_xmlfile=1.1.0
  - exceptiongroup=1.3.0
  - executing=0.8.3
  - expat=2.7.1
  - fastapi=0.116.0
  - fastapi-cli=0.0.8
  - ffmpeg=4.3
  - filelock=3.17.0
  - flask=3.1.1
  - flatbuffers=24.3.25
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - gast=0.5.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - google-pasta=0.2.0
  - grpcio=1.71.0
  - h11=0.16.0
  - h5py=3.14.0
  - hdf5=1.14.5
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.5
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.1.1
  - libcups=2.4.2
  - libcurand=10.3.10.19
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libosqp=0.6.3
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libqdldl=0.1.7
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxgboost=3.0.1
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - lightgbm=4.6.0
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.8
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ml_dtypes=0.5.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=4.0.3
  - mpich=4.1.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - namex=0.0.7
  - narwhals=1.46.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.5
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openpyxl=3.1.5
  - openssl=3.5.1
  - opt_einsum=3.3.0
  - optree=0.14.1
  - osqp=0.6.7.post3
  - overrides=7.4.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.7
  - plotly=6.2.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protobuf=5.29.3
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-xgboost=3.0.1
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - pytables=3.10.2
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=24.3.25
  - python-json-logger=3.2.1
  - python-multipart=0.0.20
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qdldl-python=0.1.7.post5
  - qtbase=6.7.3
  - qtconsole=5.6.1
  - qtdeclarative=6.7.3
  - qtpy=2.4.1
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.4
  - retrying=1.4.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rich-toolkit=0.14.8
  - rpds-py=0.22.3
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - scs=3.2.7.post2
  - seaborn=0.13.2
  - send2trash=1.8.2
  - setuptools=78.1.1
  - shellingham=1.5.4
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - starlette=0.46.2
  - statsmodels=0.14.4
  - tbb=2021.8.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - termcolor=2.1.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchtriton=3.1.0
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - typing-inspection=0.4.1
  - tzdata=2025b
  - unicodedata2=15.1.0
  - urllib3=2.5.0
  - uvicorn=0.35.0
  - uvicorn-standard=0.35.0
  - uvloop=0.21.0
  - watchfiles=0.24.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xgboost=3.0.1
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.4.0
      - category-encoders==2.8.1
      - cloudpickle==3.1.1
      - dacite==1.9.2
      - datasets==4.0.0
      - dateparser==1.2.2
      - dill==0.3.8
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - hf-xet==1.1.5
      - htmlmin==0.1.12
      - huggingface-hub==0.33.2
      - imagehash==4.3.1
      - imageio==2.37.0
      - keras==3.10.0
      - lazy-loader==0.4
      - libclang==18.1.1
      - lime==0.2.0.1
      - llvmlite==0.44.0
      - loguru==0.7.3
      - multidict==6.6.3
      - multimethod==1.12
      - multiprocess==0.70.16
      - numba==0.61.0
      - phik==0.12.4
      - propcache==0.3.2
      - puremagic==1.30
      - pyaml==25.5.0
      - pyarrow==20.0.0
      - pyod==2.0.5
      - pytz==2025.2
      - pywavelets==1.8.0
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-optimize==0.10.2
      - sentence-transformers==5.0.0
      - shap==0.48.0
      - slicer==0.0.8
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorflow==2.18.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tifffile==2025.6.11
      - tokenizers==0.21.2
      - transformers==4.53.1
      - typeguard==4.4.4
      - typing-extensions==4.14.1
      - tzlocal==5.3.1
      - visions==0.8.1
      - wordcloud==1.9.4
      - xxhash==3.5.0
      - yarl==1.20.1
      - ydata-profiling==4.16.1
