name: RAMS
channels:
  - defaults
dependencies:
  - python=3.11
  - statsmodels
  - jupyter
  - joblib
  - matplotlib
  - numpy
  - networkx
  - pytables
  - seaborn
  - notebook
  - lightgbm
  - scipy
  - tqdm
  - xgboost
  - scikit-learn
  - openpyxl
  - pandas
  - ipython
  - tensorflow
  - pytorch
  - torchaudio
  - pytorch-cuda=11.8
  - torchvision
  - typer
  - ipykernel
  - rich
  - dash
  - jupyterlab
  - fastapi
  - pydantic
  - plotly
  - cvxpy
